[package]
name = "swaptun-models"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.10", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "runtime-actix-rustls",
  "runtime-async-std-rustls",
  "macros",

] }
serde = "1.0.219"
serde_json = "1.0.140"
